[Feature - March 2nd, 2024]{POST, POSTKEYWORD} 게시글 CRUD 와 게시글_키워드 CRUD
cca-ffodregamdi/running-hi-back-v2 pull request #59
Opened 2024-03-15 10:16 UTC by silverpoodle

## 📌 관련 이슈

* closed #56 
* closed #58 

## ✨ 과제 내용

- 게시글 생성
    - 게시글 생성 시 키워드 리스트 함께 저장

- 게시글 수정
    - 게시글 수정 시 기존 키워드 리스트 삭제, 새로 저장

- 게시글 조회
    - 게시글 조회 시 등록된 키워드 리스트 함께 조회

- 게시글 삭제
    - 게시글 삭제 시 해당 키워드 리스트 삭제

## 📸 스크린샷(선택)

![image](https://github.com/cca-ffodregamdi/running-hi-back-v2/assets/88484476/089c4fdd-d1e0-4610-b4c6-56d2bbb9cedb)
- 테스트 이슈로 File 부분은 잠시 주석처리 해뒀습니다.

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들
![image](https://github.com/cca-ffodregamdi/running-hi-back-v2/assets/88484476/3e59cc35-f772-4ac4-9f89-32e2f20c72f0)
### - 게시글 수정 시 기존 키워드 리스트 삭제, 새로 저장하게 되는데 이 과정에서 @Transactional 어노테이션이 지정된 메소드를 해당 클래스 내에서 직접 호출하고 있습니다. 찾아보니 이는 지양되는 방식이라 빠른 시일 내에 수정할 예정입니다. 
- 현재는 임시로 @Transactional 을 주석처리해놨습니다.

2024-03-15 11:05 UTC, Subak-Uncle requested changes, later dismissed
도메인 상 약간의 수정이 필요해보입니다!!

2024-03-15 11:05 UTC, Subak-Uncle commented on src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/PostKeywordRepository.java
> +    void deleteAllByPostNo(@Param("postNo") Long postNo);
PostKeyword 엔티티 쪽 복합키 사용중이시라면 엔티티 내부에 복합 키에 사용되는 엔티티를 필드에 추가가 필요합니다!!

2024-03-15 11:05 UTC, Subak-Uncle commented on src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/PostKeywordRepository.java
> +    void deleteAllByPostNo(@Param("postNo") Long postNo);
추후에 수정 부탁드리겠습니다!

2024-03-15 11:05 UTC, Subak-Uncle commented on src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
> +        postKeywordService.createPostKeyword(createdPost, request.keywordList());
현재 보니까 Post aggregate와 PostKeyword aggregate의 생명주기가 동일한 것으로 보여요!! 이렇게 사용된다면 PostKeyword 엔티티가 Post aggregate 안에 속하게 이동되어야 할 것 같습니다!

2024-03-15 11:31 UTC, silverpoodle commented on src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/PostKeywordRepository.java
> +    void deleteAllByPostNo(@Param("postNo") Long postNo);
안그래도 이부분 때문에 고민이 많았는데..ㅜㅜ 복합키 대신 postKeywordNo 로 기본키를 두는게 나을까요?

2024-03-15 11:32 UTC, silverpoodle commented on src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
> +        postKeywordService.createPostKeyword(createdPost, request.keywordList());
아하 그러네요!! 수정하겠습니다!☺️

2024-03-15 11:32 UTC, Subak-Uncle commented on src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/PostKeywordRepository.java
> +    void deleteAllByPostNo(@Param("postNo") Long postNo);
그래도 좋을 것 같아요!!! 복합키 너무 어렵네요ㅠㅠㅠ

2024-03-15 11:32 UTC, silverpoodle commented on src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/PostKeywordRepository.java
> +    void deleteAllByPostNo(@Param("postNo") Long postNo);
넵넵 이 부분도 수정해놓겠습니다 감사합니다!

2024-03-15 11:33 UTC, Subak-Uncle commented on src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
> +        postKeywordService.createPostKeyword(createdPost, request.keywordList());
감사합니다!!👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

2024-03-18 05:37 UTC, numerical43 approved these changes
복합키 어렵네요ㅠ 고생하셨습니당👍

2024-03-18 05:38 UTC, merged

2024-03-18 05:39 UTC, Subak-Uncle approved these changes
수정하느라 고생하셨습ㄴ다!